//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEntity
    {
        public CourseEntity()
        {
            this.Participant = new HashSet<ParticipantEntity>();
            this.Point = new HashSet<PointEntity>();
            this.Resultat = new HashSet<Resultat>();
        }
    
        public int Id { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Ville { get; set; }
        public int MaxParticipants { get; set; }
    
        public virtual ICollection<ParticipantEntity> Participant { get; set; }
        public virtual ICollection<PointEntity> Point { get; set; }
        public virtual ICollection<Resultat> Resultat { get; set; }
    }
}
