//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointEntity
    {
        public PointEntity()
        {
            this.Resultat = new HashSet<ResultatEntity>();
        }
    
        public int Id { get; set; }
        public string Titre { get; set; }
        public int Ordre { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int CourseId { get; set; }
        public int TypePointId { get; set; }
    
        public virtual CourseEntity Course { get; set; }
        public virtual TypePointEntity TypePoint { get; set; }
        public virtual ICollection<ResultatEntity> Resultat { get; set; }
    }
}
