//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultatEntity
    {
        public int id { get; set; }
        public int idPoint { get; set; }
        public int idCourse { get; set; }
        public int idPersonne { get; set; }
        public System.DateTime temps { get; set; }
    
        public virtual CourseEntity Course { get; set; }
        public virtual PersonneEntity Personne { get; set; }
        public virtual PointEntity Point { get; set; }
    }
}
