//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypePointEntity
    {
        public TypePointEntity()
        {
            this.Point = new HashSet<PointEntity>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
    
        public virtual ICollection<PointEntity> Point { get; set; }
    }
}
